services:
  netzmacht.toolkit.listeners.hook_listener:
    class: Netzmacht\Contao\Toolkit\Listener\HookListener
    arguments:
      - '@event_dispatcher'

  netzmacht.toolkit.listeners.get_template_helpers:
    class: Netzmacht\Contao\Toolkit\View\Template\Subscriber\GetTemplateHelpersListener
    arguments:
      - '@netzmacht.toolkit.assets_manager'
      - '@cca.translator'
    tags:
      - { name: 'kernel.event_listener', event: 'netzmacht.toolkit.view.get-template-helpers'}
