services:
  netzmacht.contao_toolkit.listeners.get_template_helpers:
    class: Netzmacht\Contao\Toolkit\View\Template\Subscriber\GetTemplateHelpersListener
    arguments:
      - '@netzmacht.contao_toolkit.assets_manager'
      - '@translator'
    tags:
      - { name: 'kernel.event_listener', event: 'netzmacht.contao_toolkit.view.get_template_helpers'}

  netzmacht.contao_toolkit.listeners.create_formatter_subscriber:
    class: Netzmacht\Contao\Toolkit\Dca\Formatter\Subscriber\CreateFormatterSubscriber
    arguments:
      - []
      - []
      - []
      - '@netzmacht.contao_toolkit.dca.formatter.options_formatter'
    tags:
      - { name: 'kernel.event_listener', event: 'netzmacht.contao_toolkit.dca.create_formatter'}
