services:
  netzmacht.contao_toolkit.assets_manager:
    class: Netzmacht\Contao\Toolkit\View\Assets\GlobalsAssetsManager
    factory: ['@netzmacht.contao_toolkit.globals_assets_manager_factory', 'create']

  netzmacht.contao_toolkit.callback_invoker:
    class: Netzmacht\Contao\Toolkit\Dca\Callback\Invoker

  netzmacht.contao_toolkit.contao_config:
    class: Contao\Config
    factory: ['@netzmacht.contao_toolkit.contao_services_factory', 'createConfigService']

  netzmacht.contao_toolkit.component.content_element_factory:
    class: Netzmacht\Contao\Toolkit\Component\ToolkitComponentFactory
    arguments:
      - []

  netzmacht.contao_toolkit.component.frontend_module_factory:
    class: Netzmacht\Contao\Toolkit\Component\ToolkitComponentFactory
    arguments:
      - []

  netzmacht.contao_toolkit.contao_services_factory:
    class: Netzmacht\Contao\Toolkit\DependencyInjection\ContaoServicesFactory
    arguments:
      - '@contao.framework'

  netzmacht.contao_toolkit.contao.config:
    factory: ['@netzmacht.contao_toolkit.contao_services_factory', 'createConfigAdapter']

  netzmacht.contao_toolkit.contao.encryption:
    factory: ['@netzmacht.contao_toolkit.contao_services_factory', 'createEncryptionAdapter']

  netzmacht.contao_toolkit.contao.environment:
    factory: ['@netzmacht.contao_toolkit.contao_services_factory', 'createEnvironmentAdapter']

  netzmacht.contao_toolkit.contao.input:
    factory: ['@netzmacht.contao_toolkit.contao_services_factory', 'createInputAdapter']

  netzmacht.contao_toolkit.data.alias_generator.factory.default:
    class: Netzmacht\Contao\Toolkit\Data\Alias\FilterBasedAliasGenerator
    factory: []

  netzmacht.contao_toolkit.data.alias_generator.factory.default_factory:
    class: Netzmacht\Contao\Toolkit\Data\Alias\Factory\ToolkitAliasGeneratorFactory
    arguments:
      - '@database_connection'

  netzmacht.contao_toolkit.data.database_row_updater:
    class: Netzmacht\Contao\Toolkit\Data\Updater\DatabaseRowUpdater
    arguments:
      - '@contao.framework'
      - '@database_connection'
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@netzmacht.contao_toolkit.callback_invoker'

  netzmacht.contao_toolkit.dca.formatter.factory:
    class: Netzmacht\Contao\Toolkit\Dca\Formatter\FormatterFactory
    arguments:
      - '@event_dispatcher'

  netzmacht.contao_toolkit.dca.manager:
    class: Netzmacht\Contao\Toolkit\Dca\Manager
    arguments:
      - '@netzmacht.contao_toolkit.dca.loader'
      - '@netzmacht.contao_toolkit.dca.formatter.factory'

  netzmacht.contao_toolkit.dca.loader:
    class: Netzmacht\Contao\Toolkit\Dca\DcaLoader

  netzmacht.contao_toolkit.insert_tag.replacer:
    class: Netzmacht\Contao\Toolkit\InsertTag\IntegratedReplacer
    arguments:
      - ['@contao.controller.insert_tags']
      - []

  netzmacht.contao_toolkit.view.template_factory:
    class: Netzmacht\Contao\Toolkit\View\Template\ToolkitTemplateFactory
    arguments:
      - "@event_dispatcher"

  netzmacht.contao_toolkit.view.template_name_parser:
    class: Netzmacht\Contao\Toolkit\View\Template\ContaoTemplateNameParser

  templating.engine.contao:
    class: Netzmacht\Contao\Toolkit\View\Template\ContaoTemplateEngine
    arguments:
      - '@netzmacht.contao_toolkit.view.template_factory'
      - '@netzmacht.contao_toolkit.view.template_name_parser'

  netzmacht.contao_toolkit.globals_assets_manager_factory:
    class: Netzmacht\Contao\Toolkit\View\Assets\GlobalsAssetsManagerFactory
    arguments:
      - ['@kernel']
