services:
  netzmacht.toolkit.assets_manager:
    class: Netzmacht\Contao\Toolkit\View\Assets\GlobalsAssetsManager
    factory: ['@netzmacht.toolkit.globals_assets_manager_factory', 'create']

  netzmacht.toolkit.callback_invoker:
    class: Netzmacht\Contao\Toolkit\Dca\Callback\Invoker

  netzmacht.toolkit.contao_config:
    class: Contao\Config
    factory: ['@netzmacht.toolkit.contao_services_factory', 'createConfigService']

  netzmacht.toolkit.component.content_element_factory:
    class: Netzmacht\Contao\Toolkit\Component\ToolkitComponentFactory
    arguments:
      -

  netzmacht.toolkit.filesystem:
    class: Contao\Files
    factory: ['Contao\Files', 'getInstance']

  netzmacht.tookit.encryption:
    class: Contao\Encryption
    factory: ['Contao\Encryption', 'getInstance']

  netzmacht.toolkit.contao_services_factory:
      class: Netzmacht\Contao\Toolkit\DependencyInjection\ContaoServicesFactory
      arguments:
        - '@contao.framework'

  netzmacht.toolkit.template_factory:
    class: Netzmacht\Contao\Toolkit\View\Template\ToolkitTemplateFactory
    arguments:
      - "@event_dispatcher"

  netzmacht.toolkit.globals_assets_manager_factory:
    class: Netzmacht\Contao\Toolkit\View\Assets\GlobalsAssetsManagerFactory
    arguments:
      - ['@kernel']
